version: '3'

services:
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: minin
    ports:
      - '5432:5432'

  redis:
    image: redis
    container_name: cache
    ports:
      - '6379:6379'
    command: redis-server --bind 0.0.0.0
