name: CI

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  install:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Lint
        run: npm run lint

  audit:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Audit
        run: npm audit --audit-level=critical

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Test
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build
        run: npm run build
